FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "src/OrderProcessor/OrderProcessor.csproj"
RUN dotnet publish "src/OrderProcessor/OrderProcessor.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "OrderProcessor.dll"]
